# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activatecode',
            options={'verbose_name': '用户激活码', 'verbose_name_plural': '用户激活码'},
        ),
        migrations.AlterField(
            model_name='activatecode',
            name='expiration_time',
            field=models.DateTimeField(verbose_name='过期时间'),
        ),
    ]
