# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodulo', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, verbose_name='头像'),
        ),
    ]
