# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
